kind: pipeline
name: default

steps:
- name: clone
  image: plugins/git
  recursive: true
  submodule_override:
    docdock: https://github.com/vjeantet/hugo-theme-docdock.git

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55
    validate: true
    theme: themes/docdock
