# baseURL = "https://vielmetti.github.io/commonplace/"
languageCode = "en-us"
title = "Commonplace"
theme = "docdock"
relativeURLs = true

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[params]
   themeStyle = "original"
   editURL = "https://github.com/vielmetti/commonplace/tree/master/content/"
